// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_W5PL_4ivmQh6SLm042K9gGhb-bV7ChM',
    appId: '1:579484452561:web:a0fded0fe8207d03bf67f0',
    messagingSenderId: '579484452561',
    projectId: 'new-44f86',
    authDomain: 'new-44f86.firebaseapp.com',
    storageBucket: 'new-44f86.appspot.com',
    measurementId: 'G-XNN1Y3NWSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LnK9w1EopbEbGl2OtS80P4ubzTVAnwQ',
    appId: '1:579484452561:android:a8ce08190f0dc30ebf67f0',
    messagingSenderId: '579484452561',
    projectId: 'new-44f86',
    storageBucket: 'new-44f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAln5VNd06HTAb2Fh7QVWpNgfAeu4UUeyQ',
    appId: '1:579484452561:ios:8ef24a76462b0557bf67f0',
    messagingSenderId: '579484452561',
    projectId: 'new-44f86',
    storageBucket: 'new-44f86.appspot.com',
    iosClientId: '579484452561-c9tkqbei6o48ro15t0p9q8crcokt7glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAln5VNd06HTAb2Fh7QVWpNgfAeu4UUeyQ',
    appId: '1:579484452561:ios:8ef24a76462b0557bf67f0',
    messagingSenderId: '579484452561',
    projectId: 'new-44f86',
    storageBucket: 'new-44f86.appspot.com',
    iosClientId: '579484452561-c9tkqbei6o48ro15t0p9q8crcokt7glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
